import "./globals.css";
import { Poppins } from "next/font/google";
import Header from "./components/Header";

const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
  styles: ["italic"],
});

export const metadata = {
  title: "Next 13",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        <main className="h-screen text-center text-white bg-sky-900">
          {children}
        </main>
      </body>
    </html>
  );
}
